/**
 * Inline `content/**\/*.mdx` into a module so the app can read it without a
 * filesystem.
 *
 * `lib/content.ts` used to `readFileSync` the MDX at request time. That works
 * on a Node server and does not work on Cloudflare Workers, where `node:fs` is
 * an ephemeral per-request scratch space with nothing in it — so every
 * `/work/<slug>` and `/writing/<slug>` returned 404 on the first Worker build,
 * while the prerendered index pages looked fine. The route-level symptom was
 * ten steps from the cause, which is a good reason not to leave a runtime
 * filesystem dependency in a codebase that deploys to an edge runtime.
 *
 * Every route on this site is dynamic — `app/layout.tsx` reads `headers()` for
 * the CSP nonce (ADR-0014), and that opts the whole tree out of static
 * rendering — so "just prerender the content pages" is not available without
 * giving up the nonce. Bundling the content is the change that keeps both.
 *
 * The output is committed. A fresh clone must typecheck before anything has
 * run `prebuild`, and this is generated data the build depends on, not a build
 * artifact. `prebuild` regenerates it, so a stale bundle shows up as a dirty
 * `git status` immediately after a build rather than as wrong content in
 * production.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const CONTENT_ROOT = join(ROOT, 'content');
const OUT = join(ROOT, 'lib', 'content-bundle.generated.ts');
const TYPES = ['case-studies', 'writing'] as const;

const entries: Array<[string, string]> = [];
for (const type of TYPES) {
  const dir = join(CONTENT_ROOT, type);
  if (!existsSync(dir)) continue;
  for (const name of readdirSync(dir).sort()) {
    if (!name.endsWith('.mdx')) continue;
    const slug = name.replace(/\.mdx$/, '');
    entries.push([`${type}/${slug}`, readFileSync(join(dir, name), 'utf8')]);
  }
}

const body = entries
  .map(([key, raw]) => `  ${JSON.stringify(key)}: ${JSON.stringify(raw)},`)
  .join('\n');

const file = `// GENERATED by scripts/build-content-bundle.ts — do not edit.
// Run \`pnpm content:bundle\` (or any \`pnpm build\`) to regenerate.
//
// Keys are \`<content type>/<slug>\`; values are the raw MDX including its
// frontmatter fence. See the generator for why the content is inlined rather
// than read from disk at request time.

export const CONTENT_BUNDLE: Record<string, string> = {
${body}
};
`;

const previous = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
if (previous === file) {
  console.log(`content-bundle: up-to-date (${entries.length} files).`);
} else {
  writeFileSync(OUT, file);
  console.log(`content-bundle: wrote ${entries.length} files to lib/content-bundle.generated.ts`);
}
