/**
 * Compile every MDX body into a real JavaScript module at build time.
 *
 * The site used to render MDX with `next-mdx-remote`, which compiles the
 * source on each request and evaluates the result with `new Function`. Neither
 * half of that survives Cloudflare Workers:
 *
 *   - `new Function` is refused outright — "EvalError: Code generation from
 *     strings disallowed for this context". A Worker executes only code that
 *     was present at deploy time.
 *   - Shiki, which `rehype-pretty-code` drives, instantiates its oniguruma
 *     grammar engine from WebAssembly bytes — "Wasm code generation disallowed
 *     by embedder", for the same reason.
 *
 * Both are runtime-compilation problems and both disappear once the compile
 * happens during the build, in Node, where `new Function` and `WebAssembly`
 * are ordinary. This script does that compile and emits plain ESM that the
 * bundler treats like any other module.
 *
 * It also means highlighting and MDX parsing cost nothing per request, which
 * is the same reason most Next sites compile MDX at build time anyway. The
 * only thing lost is the ability to render MDX that did not exist at build
 * time, which this site never does — the corpus is nineteen committed files.
 *
 * Output is git-ignored: it is derived entirely from `content/**` and the
 * plugin stack in `lib/mdx-options.ts`, it is large, and it is regenerated by
 * `prebuild` and `pretypecheck` so nothing can consume a stale copy.
 */
import { compile } from '@mdx-js/mdx';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import rehypePrettyCode from 'rehype-pretty-code';
import rehypeSlug from 'rehype-slug';
import remarkGfm from 'remark-gfm';
import { stripTitleChrome } from '../lib/strip-title-chrome';

const ROOT = join(import.meta.dirname, '..');
const CONTENT_ROOT = join(ROOT, 'content');
const OUT_DIR = join(ROOT, 'lib', 'mdx', 'generated');
const TYPES = ['case-studies', 'writing'] as const;

/**
 * The same plugin stack `lib/mdx-options.ts` documents, applied here instead of
 * at request time. Kept as a literal rather than imported from that module
 * because that module types itself against `next-mdx-remote`'s option shape,
 * which is a different (and now unused) surface from `@mdx-js/mdx`'s.
 */
const REMARK_PLUGINS = [remarkGfm];
const REHYPE_PLUGINS = [
  rehypeSlug,
  [
    rehypePrettyCode,
    { theme: { light: 'github-light', dark: 'github-dark-dimmed' }, keepBackground: false },
  ],
];

function frontmatterStripped(raw: string): string {
  const fenced = /^---\r?\n[\s\S]*?\r?\n---\r?\n?([\s\S]*)$/.exec(raw);
  return fenced ? fenced[1]! : raw;
}

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const modules: Array<{ key: string; file: string; ident: string }> = [];

for (const type of TYPES) {
  const dir = join(CONTENT_ROOT, type);
  for (const name of readdirSync(dir).sort()) {
    if (!name.endsWith('.mdx')) continue;
    const slug = name.replace(/\.mdx$/, '');
    let body = frontmatterStripped(readFileSync(join(dir, name), 'utf8'));

    // The authored bodies repeat their title and dek as a leading H1 +
    // blockquote; both templates render those from frontmatter, so the pair
    // is dropped rather than shown twice. This used to happen just before
    // `MDXRemote` for writing only; it happens here now, for the same reason
    // and to the same effect. Case studies join them (D4): their dek used to
    // fall through to generic blockquote styling — a grey bar with zero
    // padding — because the detail template did not render a dek at all. It
    // renders one now, from frontmatter, so the authored copy must go.
    body = stripTitleChrome(body);

    const compiled = await compile(body, {
      remarkPlugins: REMARK_PLUGINS,
      rehypePlugins: REHYPE_PLUGINS as any,
      outputFormat: 'program',
      jsx: false,
      development: false,
    });

    const file = `${type}__${slug}.mdx.js`;
    writeFileSync(join(OUT_DIR, file), String(compiled));
    modules.push({
      key: `${type}/${slug}`,
      file,
      ident: `M${modules.length}`,
    });
  }
}

const imports = modules.map((m) => `import ${m.ident} from './${m.file}';`).join('\n');
const entries = modules.map((m) => `  ${JSON.stringify(m.key)}: ${m.ident},`).join('\n');

const index = `// GENERATED by scripts/build-mdx-modules.ts — do not edit.
// Run \`pnpm mdx:modules\` (or any \`pnpm build\`) to regenerate.
//
// Keys are \`<content type>/<slug>\`. Each value is the compiled MDX body as a
// React component, ready to render with no runtime compilation — see the
// generator for why that matters on Cloudflare Workers.
import type { ComponentType } from 'react';

${imports}

export const MDX_MODULES: Record<string, ComponentType> = {
${entries}
};

export function getMdxModule(type: string, slug: string): ComponentType | null {
  return MDX_MODULES[\`\${type}/\${slug}\`] ?? null;
}
`;

writeFileSync(join(OUT_DIR, 'index.ts'), index);
writeFileSync(
  join(OUT_DIR, 'modules.d.ts'),
  `// GENERATED by scripts/build-mdx-modules.ts — do not edit.
// The compiled bodies are plain JavaScript with no declarations of their own.
//
// The pattern is \`*.mdx.js\`, not \`*.js\`: a bare \`*.js\` wildcard is global and
// swallowed \`.open-next/worker.js\` too, typing the Cloudflare entry as a React
// component. One \`*\` is all TypeScript allows in an ambient module pattern, so
// the specificity has to come from the extension.
declare module '*.mdx.js' {
  import type { ComponentType } from 'react';
  const MDXContent: ComponentType;
  export default MDXContent;
}
`,
);

console.log(`mdx-modules: compiled ${modules.length} bodies to lib/mdx/generated/`);
